### ISSUE TITLE
today (24-04-24) r523 compilation with errors  in endevourOS (arch)

### ISSUE THREAD

**Issue by vitforlinux-gimp** [bartoszek/AUR-gimp-develop-git#5]
I'm not clear on the cause, but even when I try again the compilation ends with an error and no package.

**Comment by vitforlinux-gimp** [comment]
Sorry, I was wrong, today 26-04-24 everything worked... maybe I had too much stuff on my computer.

**Comment by bartoszek** [comment]
Or just some rough commit on the upstream repo ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯
